name: CI
on: 
  pull_request: 
    branches: 
      - "main"
  push:
    paths-ignore: 
      - "README.md"
      - ".gitignore"
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: windows-latest

    env:
      solution: pnp-tool.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Restore dependencies
        run: dotnet restore ${{ env.solution }}
  
      - name: Build
        run: dotnet build ${{ env.solution }} --no-restore -p:Platform="Any CPU"
