name: CI
on: 
  pull_request: 
    branches: 
      - "main"
  push:
    paths-ignore: 
      - "README.md"
      - ".gitignore"
    branches:
      - "main"
jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    env:
      solution: pnp-tool.sln

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
          
      - name: Restore dependencies
        run: dotnet restore ${{ env.solution }}
  
      - name: Build
        run: dotnet build ${{ env.solution }} --no-restore -p:Platform="Any CPU" -p:TreatWarningsAsErrors=True
        env:
          MDIXVersion: "0.0.0"
          MDIXColorsVersion: "0.0.0"
          MDIXMahAppsVersion: "0.0.0"
  
      - name: Test
        timeout-minutes: 20
        run: dotnet test ${{ env.solution }} --no-build --verbosity normal --blame-crash
  
  #    - name: Build NuGets
  #      run: .\Scripts\BuildNugets.ps1 -MDIXVersion ${{ inputs.mdix-version }} -MDIXColorsVersion ${{ inputs.mdix-colors-version }} -MDIXMahAppsVersion ${{ inputs.mdix-mahapps-version }}
